### ISSUE TITLE
Cannot connect to RT3000 using ROS2 driver

### ISSUE THREAD

**Issue by chris-ferone** [OxfordTechnicalSolutions/oxts_ros2_driver#2]
Hi Oxts,

I'm having trouble trying to deploy the driver using ros2 foxy. After running 

`ros2 launch oxts run.py `

the last thing I see printed to the terminal is

`Waiting for INS config information... `

I have confirmed the following already:

1. I've specified the proper IP address of the RT3000 (unit_ip rosparam) in the config.yaml before building.
2. I've confirmed I can ping the RT3000 successfully
3. Using NavDisplay, I've confirmed the RT3000 is reporting a RTK integer fix and the lat,long, alt reported looks correct.

Any suggestions on how can I further troubleshoot this issue? Thanks!

**Comment by eansell-oxts** [comment]
Hi, just to triple check you've supplied the correct IP address, could you please confirm the driver outputs something like:

```
[oxts_driver-1] [INFO] [1637841171.659255220] [oxts_driver]: Connecting: 1.2.3.4:3000
```

(Where `1.2.3.4:3000` is the IP address and port you're trying to use.)

I mention this because secondly, there's no need to build the driver after editing the configuration file. I'm guessing that what you're doing is editing the file in the repository, then building it. Suppose your workspace looks like `./ros_ws/src/oxts_ros2_driver/...`. The file `./ros_ws/src/oxts_ros2_driver/oxts_ins/config/default.yaml` is just a default file to be copied over during the build process (`colcon build`).

The intended way to configure the driver is to edit e.g. `./ros_ws/install/oxts_ins/share/oxts_ins/config/default.yaml` after building. This file is what's actually read by the driver when starting up (and is where the former is copied to when building). The README should be clearer about this.

It is possible you have edited the wrong file. Is the correct IP address printed to the terminal?

**Comment by SSouliman** [comment]
Hi Chris,

Further to the above, what might be happening is that the ROS driver, for some reason or another, is not connecting to the unit. 

Could you please check the following:

1. What is the config file name, inside oxts_driver, that's being used? You mentioned config.yaml, ,but the driver will be looking for default.yaml.

2. If you still have issues, is it possible to get the .yaml file over so we can check?

Regards,

**Comment by chris-ferone** [comment]
@SSouliman  I misspoke. The file I was referring to is ros2_ws/src/oxts_ros2_driver/oxts_driver/config/default.yaml. Github won't allow me to attach a .yaml file, but the only line I changed in it is line 6, and set it to my unit's IP address of 195.0.0.12. @eansell-oxts here's a screenshot showing the driver output. 
![oxts_debug](https://user-images.githubusercontent.com/26842614/143872898-cbab220f-bb66-4ecd-b31e-f516f515cde9.png)
I also forgot to mention in my original post I verified the NCOM data rate is set to 100Hz. 
![oxts_debug2](https://user-images.githubusercontent.com/26842614/143873616-e26cbc13-f3fb-4280-9bb7-2ee38637bd32.png)

**Comment by chris-ferone** [comment]
@eansell-oxts just to further follow-up on your comment, the README is clear. My preference was to edit the yaml in the src folder because that folder is under version control and the install folder is not (under version control). Hence, the reason why I made sure to build after editing the yaml file in the src folder so the changes got copied over to the install folder. In any case, as you can see in the screenshot in the previous post, the correct IP address is being printed in the terminal when I launch everything.

**Comment by ljones-oxts** [comment]
Hi Chris

For us to help diagnose this further, could you add the following to the `/src/oxts/oxts_driver/CMakeLists.txt` file:

`add_compile_definitions(EXTRA_DETAIL)`  

Once this is done, please rebuild and run again. This preprocessor definition will add additional debug information, and will help us diagnose whether or not the driver is receiving any data from that IP address. From there, we can direct our troubleshooting.

Additionally, so I can confirm or rule out: does the IP address of your machine share the same subnet as your unit? 

Regards

Llyr

**Comment by chris-ferone** [comment]
It turns out there's nothing wrong the with the driver. I was having trouble because I forgot the argument to use the host network in my docker container, in which I'm spooling up the driver. So while I was able to ping the RT3000 from the host machine running the docker container, I wasn't able to ping it from within the docker container. Once I added the `--network host` argument to my `docker run` command, I could ping the RT3000 from within the docker container and I was able to see nav_sat_fix msg echoed properly. Sorry for all the confusion.

**Comment by ljones-oxts** [comment]
Thanks @chris-ferone for clarifying what the root cause of the problem was and the steps you took to fix it. It's good for us to know in case others run into it when running on a dockerized setup. I'm glad it's all working for you now.

Regards,

Llyr
